-- put the question number in a comment please like so

SELECT 
	S.CUSTOMER_ID AS C_ID,
	SUM(M.PRICE) AS TOTAL_SPENT
FROM SALES AS S
JOIN MENU AS M ON S.PRODUCT_ID = M.PRODUCT_ID
GROUP BY C_ID
ORDER BY TOTAL_SPENT DESC;